name: healthysense
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter

  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  flutter_login_facebook: ^1.6.2
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  google_sign_in: ^5.0.7
  lottie: 1.2.1
  flutter_switch: ^0.3.2
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  supabase: ^0.2.10
  material_design_icons_flutter: ^6.0.7096
  url_launcher: 6.0.20
uses-material-design: true

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter:
  assets: 
    - assets/
    - assets/images/
    - assets/lottieFiles/

